package com.sugbotek.gniylf.noiprocs.yeknom.guardianlibrary

import java.io.Serializable

data class GuardianUser(
    var instanceId: String = "",
    var userId: Int = 0,
    var userPassword: String = "",
    var fcmToken: String = "",
    var apiToken: String = "",
    val roleId: ArrayList<Int> = ArrayList(),
    var callSign: String = "",
    var email: String = "",
    var firstName: String = "",
    var middleName: String = "",
    var lastName: String = "",
    var mobile1: String = "",
    var mobile2: String = "",
    var gender: String = "",
    var profilePic: String = "",
    var birthDate: String = "",
    var bloodTypeId: String = "",
    var isResponder: Int = 0,
    var isApprovedResponder: Int = 0,
    var homeLatitude: String = "",
    var homeLongitude: String = "",
    var homeAddress: String = "",
    var homePhone: String = "",
    var officeLatitude: String = "",
    var officeLongitude: String = "",
    var officeAddress: String = "",
    var officePhone: String = "",
    var commandCenterId: Int = 0,
    var commandCenterName: String = "",
    var guardianName: String = "",
    var guardianMobile: String = "",
    var guardianAddress: String = "",
    var securityPin: String = "",
    var sssNumber: String = "",
    var philhealthNumber: String = "",
    var height: String = "",
    var weight: String = "",
    var eyeColor: String = "",
    var hairColor: String = "",
    var birthMark: String = "",
    var built: String = "",
    var civilStatus: String = "",
    var rankId: Int = 0,
    var rankStar: Int = 0,
    var rankName: String = "",
    var hasTestCall: Int = 1,
    var insuranceProvider: String = ""
): Serializable